# Generated by Django 2.2 on 2020-05-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selfhelp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('book_name', models.CharField(max_length=40)),
                ('date', models.DateField()),
                ('genre', models.CharField(max_length=40)),
                ('pages', models.IntegerField()),
                ('rating', models.FloatField()),
                ('summary', models.TextField(max_length=1000)),
                ('Book_cover', models.ImageField(upload_to=None)),
            ],
        ),
    ]
