# Generated by Django 2.2 on 2020-05-04 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfhelp',
            name='date',
        ),
    ]
