# Generated by Django 2.2 on 2020-05-04 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0003_remove_selfhelp_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhelp',
            name='Book_cover',
            field=models.ImageField(default='SOME STRING', height_field=100, upload_to='images/', width_field=100),
        ),
        migrations.AddField(
            model_name='selfhelp',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
