# Generated by Django 2.2 on 2020-05-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0004_auto_20200504_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhelp',
            name='Book_cover',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
