# Generated by Django 2.2 on 2020-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0005_auto_20200504_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='selfhelp',
            name='summary',
            field=models.TextField(max_length=5000),
        ),
    ]
