# Generated by Django 2.2 on 2020-05-04 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selfhelp', '0006_auto_20200504_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Home',
        ),
    ]
